#ifndef ARC_LIBARCHIVE_NS_H_
#define ARC_LIBARCHIVE_NS_H_

#include "../arc_ns.h"


#define ARC_PLUGIN_LIBARCHIVE_NS_BEGIN ARC_PLUGIN_NS_BEGIN namespace LibArchive {
#define ARC_PLUGIN_LIBARCHIVE_NS_END } ARC_PLUGIN_NS_END

#endif /* ARC_LIBARCHIVE_NS_H_ */
