#undef TEMPLATE_ARG
#undef TEMPLATE_ARGS_1
#undef TEMPLATE_ARGS_2
#undef TEMPLATE_ARGS_3
#undef TEMPLATE_ARGS_4
#undef TEMPLATE_ARGS_5
#undef TEMPLATE_ARGS_6
#undef TEMPLATE_ARGS_7
#undef TEMPLATE_ARGS_8
#undef TEMPLATE_ARGS_9
#undef TEMPLATE_ARGS_10

#undef ARGUMENT
#undef ARGUMENTS_1
#undef ARGUMENTS_2
#undef ARGUMENTS_3
#undef ARGUMENTS_4
#undef ARGUMENTS_5
#undef ARGUMENTS_6
#undef ARGUMENTS_7
#undef ARGUMENTS_8
#undef ARGUMENTS_9
#undef ARGUMENTS_10

#undef VALUE
#undef VALUES_1
#undef VALUES_2
#undef VALUES_3
#undef VALUES_4
#undef VALUES_5
#undef VALUES_6
#undef VALUES_7
#undef VALUES_8
#undef VALUES_9
#undef VALUES_10
